DROP TABLE IF EXISTS CONTACT_TEL_DETAIL;
DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS SCORES;

CREATE TABLE CONTACT (
       ID SERIAL NOT NULL
     , FIRST_NAME VARCHAR(20) NOT NULL
     , LAST_NAME VARCHAR(20) NOT NULL
     , BIRTH_DATE DATE
     , VERSION INT NOT NULL DEFAULT 0
     , CONSTRAINT UQ_CONTACT_1 UNIQUE(FIRST_NAME, LAST_NAME)
     , PRIMARY KEY (ID)
);

CREATE TABLE CONTACT_TEL_DETAIL (
       ID SERIAL NOT NULL
     , CONTACT_ID INT NOT NULL
     , TEL_TYPE VARCHAR(20) NOT NULL
     , TEL_NUMBER VARCHAR(20) NOT NULL
     , VERSION INT NOT NULL DEFAULT 0
     , CONSTRAINT UQ_CONTACT_TEL_DETAIL_1 UNIQUE(CONTACT_ID, TEL_TYPE)
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_CONTACT_TEL_DETAIL_1 FOREIGN KEY (CONTACT_ID)
                  REFERENCES CONTACT (ID)
);

CREATE TABLE SCORES (
       ID SERIAL NOT NULL
     , CONTACT_ID INT NOT NULL
     , COURSE_NAME VARCHAR(50) NOT NULL
     , SCORE INT NOT NULL
     , SCORE_DATE DATE
     , VERSION INT NOT NULL DEFAULT 0
     , CONSTRAINT UQ_CONTACT_SCORE_DETAIL_1 UNIQUE(CONTACT_ID, SCORE)
     , PRIMARY KEY (ID) 
     , CONSTRAINT FK_CONTACT_SCORE_DETAIL_1 FOREIGN KEY(CONTACT_ID)
                  REFERENCES CONTACT (ID) 
);
